name: Run tests on PR

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Yarn install
        run: yarn

      - name: Run tests
        run: yarn test
